var a=6;
var c=7;
var b=6;
var d="6";
console.log(a + "==" + b + ":")
console.log(a==b);
console.log("<br>");
console.log(a + "!=" + b + ":");
console.log(a!=b);
console.log("<br>");
console.log(a + "!=" + c + ":");
console.log(a!=c);
console.log("<br>");
console.log(a + "<" + c + ":");
console.log(a<c);
console.log("<br>");
console.log(a + ">" + c + ":");
console.log(a>c);
console.log("<br>");
console.log(b + "==" + d + ":");
console.log(b==d);
console.log("<br>");